
# Cleaning Dataset 

Perform data cleaning on the SYNCH Rapid City Dataset, including formating the variable names, spell checking.

In [9]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Import library

In [10]:

from sentence_transformers import SentenceTransformer, util , SimilarityFunction
from pathlib import Path


import pandas as pd
import numpy as np
import regex as re
import itertools as it
import matplotlib.pyplot as plt
import pickle
import os
import torch
import seaborn as sns 
import sys
import json
import networkx as nx

In [11]:

# Get the current working directory
cwd = Path.cwd()

# Get the path to the parent directory
parent_dir = cwd.parent

# Add the parent directory to the Python path
sys.path.append(str(parent_dir))

# Now you can import the data_io module from src
import src.data_io as data_io
import src.cld_nx as cld_nx

# Read data

In [12]:
print(os.getcwd())

/Users/gl665/PycharmProjects/Phrame_MentalMaps/notebook

## Read Raw data

In [13]:
# Go one level up from the current directory
# cwd = os.getcwd()

# parent_dir = Path(cwd).parent
# print(parent_dir)

# my_data_RC = {}
# folder_path = str(parent_dir / 'results/SYNCH/JSON_file/RC/')


# cld_data = data_io.read_json(folder_path, my_data_RC)

## Read clean data

In [14]:
cwd = os.getcwd()

parent_dir = Path(cwd).parent
print(parent_dir)

my_data = {}
folder_path = str(parent_dir / 'results/SYNCH/JSON_file/RC/clean')


cld_data = data_io.read_json(folder_path, my_data)

/Users/gl665/PycharmProjects/Phrame_MentalMaps
load: DSS full clean_edited.json
load: Passages Clean_edited.json
load: Wavi combined clean_edited.json
load: full circle clean_edited.json

In [15]:
# dict_cld = {name_file: nxgraph}

dict_cld = {}

for k, v in my_data.items():
    cld_list, G_cld = cld_nx.get_cld_graph(my_data, k)
    # cld_name = dict_file_rename.get(k, "")
    dict_cld[k] = G_cld

list_of_G = list(dict_cld.values())

for k, v in dict_cld.items(): 
    print(k, ":", v)

DSS full clean_edited.json : DiGraph with 85 nodes and 181 edges
Passages Clean_edited.json : DiGraph with 18 nodes and 61 edges
Wavi combined clean_edited.json : DiGraph with 35 nodes and 78 edges
full circle clean_edited.json : DiGraph with 77 nodes and 182 edges

## Read already preprocessed data

In [ ]:
# read the data 
# file_path = "results/SYNCH/JSON_file/RC_cld_data_cleaned_preprocessed.json"

# # Pickle dump the cld_data_new dictionary
# with open(file_path, "rb") as file:
#     cld_data = pickle.load(file)

# print(cld_data)

# Read Variable dicitionary, variable name and definition

In [16]:
# results/SYNCH/JSON_file/RC/clean/Wavi combined clean_edited.json

# import json

cwd = os.getcwd()

parent_dir = Path(cwd).parent

dict_def = {}
file_path = str(parent_dir /'results/SYNCH/JSON_file/RC/results sheets/data_dictionary/')

for file in os.listdir(file_path):
    if file.endswith(".json"):
        with open(file_path + "/" + file, 'r') as f:
            data = json.load(f)
            dict_def[file] = data

# with open(file_path, 'rb') as f:
#     data = json.load(f)

In [17]:
dict_def.values()

dict_values([{"Adverse childhood experiences - can include child abuse or neglect, but more broadly also includes general lack of stability, safety, and healthy upbriniging in one's home, as well as exposures to chronic stressors and overall family maladjustment ": 'adverse childhood experiences', 'using alcohol - in reference to misuse': 'alcohol misuse', 'positive norms for alcohol use/misuse - percieved acceptability within the community/social circles': 'alcohol use norms', 'using alcohol while pregnant': 'alcohol exposed pregnancy', "the accuracy of a caseworker's assessment of cllient needs": 'accuracy of child protective services assessment', "Being held responsible for one's actions by others": 'accountability', "individuals' ability to receive a resource that is required for fufilling DSS obligations": 'ability for parent to obtain required resource in child welfare case time frame', 'availability of family members with whom a child taken into DSS custody can be placed with': 'availability of family member safe homes for child placement during welfare case', "the extent to which an attourney understands both DSS and their clients' needs": 'attorney perception', 'the extent to which the attourney percieves that they should comply / work with DSS': 'attorney buy-in', 'the skill of an attourney (usually in reference to helping clients extend time for requirements, helping with reunification, advocating for the client, ect)': 'attorney skill', 'the extent to which an attourney intervenes with a CPS court case - usually inreference to the length of the case (not length of time for requirements)': 'attorney interference', 'pregnant women admiting alcohol consumption to hospital workers': 'admitting drug or alcohol use to healthcare workers', 'legal suspension of parental custody - children being placed in the custody of others (e.g., other family members, foster homes, group homes)': 'children removed from house', "children witnessing violence between one's parent(s) ": 'children witness intimate partner violence', 'children being in the custody of their parents': 'child home with parents', 'the quality of safety in a home for children - e.g., lack of abuse, neglect, danger, and presence of positive parenting to fufill all needs': 'child home safety', 'Overall familial health through healthy interpersonal interaction, family stability, safety, and cohesiveness - taken from the perspective of a child': 'childhood home functioning', "children in DSS custody being placed in a relative's home": 'child placed with others in family', 'the extent to which children have behavioral issues that may be difficult to manage': 'child behavioral issues', 'childhood experiences of trauma ': 'child trauma', 'children placed in custody of foster home during DSS case/after termination of parental rights': 'child placed in fostercare', 'children who remain in foster care until they are 18 years old': 'child aged out of foster care', 'age of child ': "child's age", 'number of cases for an indiviudal caseworker': 'child protective services caseworker caseload', 'stress experienced by caseworkers due to job': 'child protective services caseworker stress', 'for every child protective services position, the number of people who have filled that role over a set amount of time, either for an individual case or for an individual position.  ': 'child protective services caseworker turnover', 'caseworker salary': 'child protective services caseworker salary', 'the quality of a child protective service casewoker in managing cases - accurate assessment, building relationships with clients, providing resources, helping clients meet requirements, facilitating reunification': 'child protective services case management quality', 'longstanding mistrust between Indigenous community and DSS - a culmination of the racial divide between clientele and caseworkers, as well as the historical legacy of child removal in Indigenous communities, and the contemporary overrepresentation of Indigenous clients within the DSS system': "indigenous peoples' mistrust of child welfare services", 'resources that are legally mandated for individuals to receive and to complete/engage with': 'court mandated resources', 'completing engagement with resources': 'completing resource engagement', 'achieving all requirements set forth by DSS to be reunified with children - this includes: behavioral change for parent(s), having a safe house that poses no danger to child, haivng parents obtain self-suffiency, knowledge of healthy parenting, having no indivdiuals in house that are danger to child': 'parents completing child protective services case requirements', 'Working with DSS to fuffil all requirements': 'parents cooperating with child protective services', 'having to "start from the beginning" of all steps required to be fufilled by DSS in the middle of a case - (time limit does not extend, but the process does)': 'child protective service case timeline restart', "evaluation of clients' needs/deficits required for providing adequate childcare": 'child protective services assessment', 'DSS getting involved with a child and parent due to a reportable incident of child endangerment': 'child welfare system intervention', 'social supportive people ("natural supports" that DSS caseworkers help identify for clients to help clients have a prosocial, supportive network': 'social supports identified by child protective service caseworkers for client case progress', 'receiving a steady source of economic support that is sufficient to address financial needs': 'ecconomic stability', 'associating with prosocial friends/social supports/DSS-identitifed supports': 'engagement with prosocial support network', 'ending a relationship with a violent partner': 'ending violent relationship', 'drug /alcohol testing of patients': 'drug or alcohol testing patients during prenatal visits or labor and delivery', 'perpetration/victimization of violence by a or to a romantic partner through physical, sexual, mental/psychological, financial, social means': 'intimate partner violence', 'percieved acceptance of IPV ': 'intimate partner violence norms', 'reporting IPV to police': 'reporting partner violence event to police', 'an individual going to jail / prison due to being arrested and convicted of a crime': 'incarceration', 'judge extending the length of time an individual has to fuffill DSS requirements': 'judge extending the time a person has to fufill child protective services requirements', 'judge positive evaluation of parent - usually in reference to observing parent actively working towards addressing all DSS requirements/having the ability to address all requirements': 'judge positive perception of parent', 'visitation with child during a DSS case when child is in custody somewhere else': 'parent visiting child during child welfare case', 'the length of time that an individual has to fufill all DSS requirements ': 'length of time allowed for a client to fufill all requirements during child welfare case', 'receiving housing or obtaining housing that is fit and safe to live in': 'living in a house that is legally safe to live in', 'deficits related to having positive mental health - e.g., increases involve higher mental illnesses or negative emotionality': 'mental health needs', 'actively looking for resources to address mental health needs': 'mental health resource seeking', 'parental change of behavior that is associated with what is necessary for an acceptable parent/child care (e.g., nonviolence, sobriety, mental health, self-sufficiency and self-care and competent care of others': 'parent positive behavior change', 'improving relationship with a romantic partner to reduce / eliminate violence and improve overall relationship functioning/health': 'improving relationship with a romantic partner where violence is stopped', 'lack of trust of  legal institution(s) - courts, police, justice system, social services, etc.': 'mistrust of law', 'legal violations / incidents that occur when parents are actively engaged with DSS': 'legal violations that occur when parents are actively engaged with the child welfare system', 'actually receiving/engaging with resources to help address needs': 'obtaining resources', 'if a parent has custody of other children when they become involved/are involved in a DSS case': 'other children in care', 'quality of the relationship that children have with their parents - an "increase" indicates a healthier relationship': 'quality of relationship between parent and child', 'trauma in reference to stress and negative experiences with DSS/child removal': 'trauma from having child removed from home by child welfare system', 'stress caused by having to fufill dss requirements, work with dss, miss children': 'parent stress from engagement with child welfare system', 'a high-quality working relationship between parent and caseworker - e.g., cooperative, responsive, trustful': 'positive relationship between parent and child protective services caseworker', "ones' personal attitudes (here as positive) towards DSS as helpful/good": "person's positive perception of child welfare system", 'distance between where a parent is and where their child is lliving during a DSS case': 'distance between a parent and where a child is placed to live during a child welfare case', 'previous experiences with DSS - usually as a case/client': 'prior experience as a child protective services client', 'using multiple drugs, or using alcohol and other drugs': 'polysubstance use', 'in reference to kid visits - the quality of the parent-child interaction during visits': "quality of a parent's visit with their child during a child welfare case", 'starting to drink alcohol or use drugs again after a period of sobriety': 'relapse', 'NaN': 'social support from relatives', 'the extent to which resources have a positive influence on behavior change - address needs as assessed by DSS': 'resource impact', 'the availability (ability to easily obtain) resources that are reccomended/required to obtain by DSS': 'resource availability', 'the extent to which resources can effectively help clients meet their actual needs (regardless of the needs assessed by DSS)': 'resource efficacy to meet needs', 'parent regaining custody of child': 'parental reunification', 'the fit between the needs that resources reccomended by DSS will address and the actual needs of the client': 'reccomendation-resource need fit', 'the time between when resources are reccomended and when they are actually able to be obtained by clients': 'gap in time between when a resource is reccomended and obtained', 'the extent of the deficits/needs of a client to become a competent parent - in terms of both quantity (number of needs) and quality (e.g., severe mental health and addiction issues vs only an issue with housing)': 'severity of child protective services assessment', 'resources reccomended by DSS': 'service reccomendations', 'caseworker reports that are used in court that are positive - demonstrating the client is actively working towards fufililing DSS requirements/is able to fufill requirements': 'supportive caseworker reports', 'leaving a violent partner': 'separation from violent partner', 'abstaining from alcohol/drug use after using (e.g., recovery from an addiction)': 'sobriety', 'child placement in care after parental rights are terminated - with family , fostercare, etc': 'child permanent housing placement after parental rights are terminated', 'a parent not completing requirements for DSS within a specific time limit, usually resulting in termination of parental rights': 'time frame for parent to fufill child protective service requirements expiring', 'Tribal court ability to manage a case/provide wellbeing for child/facilitate reunification': 'tribal management of case', 'Tribal court taking over DSS - usually as part of the Indian Child Welfare Act': 'tribal interference'}, {"Being held responsible for one's actions by others": 'accountability', 'using alcohol - in reference to misuse': 'alcohol misuse', 'Strategies and ability to carry out strategies related to dealling with internal and external negative experiences, broadly related to behavioral and emotional/mental regulation and resiliency': 'coping skills', 'Long-term Situtations/experiences that cause extreme stress or trauma, facilitate substancial consequences, or otherwise require "survival"': 'dire situations', 'using drugs -in reference to misuse': 'drug misuse', 'death': 'death', 'The mental/emotional health  of the family. Could refer to family raised in (as child) or family as an adult (e.g., with spouse and child). ': 'family emotional health', 'legal suspension of parental custody - children being placed in the custody of others (e.g., other family members, foster homes, group homes)': 'losing family and children through justice or child welfare system involvement', 'Placing faith in a higher power for guidance, feeling security and love from a higher power ': 'belief in a higher power', 'an individual going to jail / prison due to being arrested and convicted of a crime': 'incarceration', 'perpetration/victimization of violence by a or to a romantic partner through physical, sexual, mental/psychological, financial, social means': 'intimate partner violence', '"Increases" in mental health indicate a decline in negative emotions/mental illness and a rise in positive emotionality': 'mental health', 'Romantic partners who are  harmful and many perpetuate IPV - those who typically have issues with emotions or behaviors themselves': 'harmful romantic partners', 'a halfway house for women who get out of prison': 're-entry facility', 'Both professional and non-professional individuals (but in this case mostly professional or within a professional/setting) who provide you with emotional and possibly practical support': 'supportive people', 'In reference to the specific halfway house participants were in - providing stability and structure in their daily lives within a supportive and nurturing environment': 'resources that provide structure and support'}, {"Adverse childhood experiences - can include child abuse or neglect, but more broadly also includes general lack of stability, safety, and healthy upbriniging in one's home, as well as exposures to chronic stressors and overall family maladjustment ": 'adverse childhood experiences', 'using alcohol - in reference to misuse': 'alcohol misuse', 'Percieved acceptability of therapy as a solution/form of help ': 'approval of therapy', "From the perspective of the parent - observing one's child abused by others (typically by a partner) or abusing a child oneself": 'child being abused in home', 'The rate of alcohol misuse within the community': 'community alcohol misuse rate', 'The extent to which alcohol misuse is accepted in the community - alcohol misuse norms (permissive/positive)': 'community acceptance of alcohol misuse', 'The extent to which intimate partner violence is accepted in the community - intimate partner violence norms (positive/permissive) - can also be considered the extent to which intimate partner violence is seen as an acceptable solution to conflict resolution': 'community acceptance of intimate partner violence', 'The rate of intimate partner violence within the community': 'community intimate partner violence rate ', 'Going to relationship therapy with partner': "couple's therapy", 'Strategies and ability to carry out strategies related to dealling with internal and external negative experiences, broadly related to behavioral and emotional/mental regulation and resiliency': 'coping skills', 'Legal mandate that is a requirement for resolving a legal issue (e.g., probation, DSS). Usually requires receiving and successfully completing treatment ,but also can be to secure housing, employment, etc.': 'court order', "observing the cycles of violence and/or substance use over generations within one's own family, and the desire to not to contribute to this cycle by perpetuating / experiencing more violence / substance use - typically in reference to a fear of transmission of this cycle to one's children": 'desire to stop family cycle of violence and alcohol misuse', 'Intervention by child welfare/child protective services due to endangement of a child': 'child welfare system intervention', 'Overall familial health through healthy interpersonal interaction, family stability, safety, and cohesiveness - taken from the perspective of an adult family member': 'family functioning', 'having a healthy internal working model - e.g., what a healthy partner "looks like", how one should be treated by their partner and how they should treat their partner in a healthy, nonviolent, and loving way': 'knowledge about healthy relationships', 'A lack of social interaction/social support from others - typically in reference to losing friends or family as a consequence of being with a violent partner (who "cuts off" a victim from others)': 'isolation', "children witnessing violence between one's parent(s) ": 'children witness intimate partner violence', 'legal suspension of parental custody - children being placed in the custody of others (e.g., other family members, foster homes, group homes)': 'children removed from house', 'perpetration/victimization of violence by a or to a romantic partner through physical, sexual, mental/psychological, financial, social means': 'intimate partner violence', 'leaving a violent partner/ending a relationship with a violent partner': 'leaving violent partner', '"Increases" in mental health indicate a decline in negative emotions/mental illness and a rise in positive emotionality': 'mental health', 'resources to help with mental health needs e.g., therapy': 'mental health resources', 'involvement with the justice system (e.g., getting arrested)': 'legal troubles', 'the extent to which a partner is ammenable to, or actively desires to, change their behaviors / the way they interact with their partner/ to improve the relationship and reduce intimate partner violence within the relationship': 'partner willingness to change', "willpower, perseverence, related to the ability to change ones' behavior or situations, or to endure stress": 'personal strength', 'family members or friends who enable an abusive partner (either delliberate, such as retaliating against victims who call the police, or complicitly, through staying silient and giving covert approval)': 'family and friend permissive intimate partner violence norms', "Domination and control over one's partner, through physical, emotional, financial, social, or other means": 'partner power and control over person', 'the interpersonal health of a romantic relationship - e.g., communication, boundaries, cooperation, support, conflict resolution': 'healthy relationship functioning', 'informal (family/friends/mentors) and formal individuals who offer emotional or practical support - as well as those who can advocate and stand up for individuals when victimized': 'healthy support system', 'the ability to support oneself by obtaining and meeting all needs (both basic and more intrinsic, such as mental health or emotional needs)': 'being self sufficient', 'any experience (typically related to environments one is in/ traumatic experiences) that triggers stress ': 'stressful events', 'the availability and accessibility of sober social circles, functions, and activities within the community - usually in reference to the extent to which alcohol plays a role in social environments': 'sober environments', 'Quality of the way that individuals are treated by child welfare caseworkers': 'negative treatment by child welfare case workers', 'wanting to stop being victimized within an intimate partner violence relationship': 'wanting the violence by a partner or in a family to stop', 'internal or external stigma experienced due to being victimized by a partner': 'victimization

# Single CLD view

In [18]:
cld_data

{'DSS full clean_edited.json': [{1: 'ability for parent to obtain required resource in child welfare case time frame',
   2: 'accountability',
   3: 'accuracy of child protective services assessment',
   4: 'admitting drug or alcohol use to healthcare workers',
   5: 'adverse childhood experiences',
   6: 'alcohol exposed pregnancy',
   7: 'alcohol misuse',
   8: 'alcohol use norms',
   9: 'attorney buy-in',
   10: 'attorney interference',
   11: 'attorney perception',
   12: 'attorney skill',
   13: 'availability of family member safe homes for child placement during welfare case',
   14: 'child aged out of foster care',
   15: 'child behavioral issues',
   16: 'child home safety',
   17: 'child home with parents',
   18: 'child permanent housing placement after parental rights are terminated',
   19: 'child placed in fostercare',
   20: 'child placed with others in family',
   21: 'child protective service case timeline restart',
   22: 'child protective services assessment',
   23: 'child protective services case management quality',
   24: 'child protective services caseworker caseload',
   25: 'child protective services caseworker salary',
   26: 'child protective services caseworker stress',
   27: 'child protective services caseworker turnover',
   28: 'child trauma',
   29: 'child welfare system intervention',
   30: "child's age",
   31: 'childhood home functioning',
   32: 'children removed from house',
   33: 'children witness intimate partner violence',
   34: 'completing resource engagement',
   35: 'court mandated resources',
   36: 'distance between a parent and where a child is placed to live during a child welfare case',
   37: 'drug or alcohol testing patients during prenatal visits or labor and delivery',
   38: 'ecconomic stability',
   39: 'ending violent relationship',
   40: 'engagement with prosocial support network',
   41: 'gap in time between when a resource is reccomended and obtained',
   42: 'improving relationship with a romantic partner where violence is stopped',
   43: 'incarceration',
   44: "indigenous peoples' mistrust of child welfare services",
   45: 'intimate partner violence',
   46: 'intimate partner violence norms',
   47: 'judge extending the time a person has to fufill child protective services requirements',
   48: 'judge positive perception of parent',
   49: 'legal violations that occur when parents are actively engaged with the child welfare system',
   50: 'length of time allowed for a client to fufill all requirements during child welfare case',
   51: 'living in a house that is legally safe to live in',
   52: 'mental health needs',
   53: 'mental health resource seeking',
   54: 'mistrust of law',
   55: 'obtaining resources',
   56: 'other children in care',
   57: 'parent positive behavior change',
   58: 'parent stress from engagement with child welfare system',
   59: 'parent visiting child during child welfare case',
   60: 'parental reunification',
   61: 'parents completing child protective services case requirements',
   62: 'parents cooperating with child protective services',
   63: "person's positive perception of child welfare system",
   64: 'polysubstance use',
   65: 'positive relationship between parent and child protective services caseworker',
   66: 'prior experience as a child protective services client',
   67: "quality of a parent's visit with their child during a child welfare case",
   68: 'quality of relationship between parent and child',
   69: 'reccomendation-resource need fit',
   70: 'relapse',
   71: 'reporting partner violence event to police',
   72: 'resource availability',
   73: 'resource efficacy to meet needs',
   74: 'resource impact',
   75: 'separation from violent partner',
   76: 'service reccomendations',
   77: 'severity of child protective services assessment',
   78: 'sobriety',
   79: 'social support from relatives',
   80: 'social supports identified by child protective service caseworkers for client case progress',
   81: 'supportive caseworker reports',
   82: 'time frame for parent to fufill child protective service requirements expiring',
   83: 'trauma from having child removed from home by child welfare system',
   84: 'tribal interference',
   85: 'tribal management of case'},
  {45: {7: {'weight': 1},
    33: {'weight': 1},
    71: {'weight': 1},
    52: {'weight': 1}},
   7: {45: {'weight': 1}, 6: {'weight': 1}, 52: {'weight': 1}},
   71: {43: {'weight': 1}, 29: {'weight': 1}},
   52: {45: {'weight': 1},
    7: {'weight': 1},
    57: {'weight': -1},
    53: {'weight': 1}},
   31: {8: {'weight': -1},
    46: {'weight': -1},
    52: {'weight': -1},
    28: {'weight': 1}},
   8: {7: {'weight': 1}},
   46: {45: {'weight': 1}},
   5: {31: {'weight': -1}},
   66: {32: {'weight': 1}, 63: {'weight': -1}, 77: {'weight': 1}},
   32: {28: {'weight': 1},
    20: {'weight': 1},
    58: {'weight': 1},
    83: {'weight': 1}},
   79: {31: {'weight': 1}},
   6: {37: {'weight': 1}, 4: {'weight': 1}},
   33: {71: {'weight': 1}, 29: {'weight': 1}},
   57: {82: {'weight': -1},
    78: {'weight': 1},
    42: {'weight': 1},
    75: {'weight': 1},
    38: {'weight': 1},
    47: {'weight': 1},
    49: {'weight': -1},
    81: {'weight': 1}},
   84: {82: {'weight': 1}, 85: {'weight': 1}},
   2: {57: {'weight': 1}},
   78: {7: {'weight': -1}, 16: {'weight': 1}, 61: {'weight': 1}},
   42: {39: {'weight': 1}},
   75: {39: {'weight': 1}},
   39: {45: {'weight': -1}, 16: {'weight': 1}},
   63: {62: {'weight': 1}, 65: {'weight': 1}},
   36: {59: {'weight': -1}},
   59: {67: {'weight': 1},
    61: {'weight': 1},
    28: {'weight': 3},
    62: {'weight': 1}},
   68: {67: {'weight': 1}, 31: {'weight': 1}, 28: {'weight': 3}},
   67: {68: {'weight': 1}},
   41: {55: {'weight': -1},
    1: {'weight': -1},
    49: {'weight': 1},
    58: {'weight': 1},
    62: {'weight': -1}},
   4: {29: {'weight': 1}},
   37: {29: {'weight': 1}},
   56: {77: {'weight': 1}},
   77: {32: {'weight': 1}, 17: {'weight': -1}},
   38: {16: {'weight': 1}, 61: {'weight': 1}},
   16: {77: {'weight': -1},
    31: {'weight': 1},
    5: {'weight': -1},
    61: {'weight': 1}},
   60: {17: {'weight': 1}, 63: {'weight': 1}},
   10: {82: {'weight': 1}},
   20: {36: {'weight': -1}, 28: {'weight': -1}, 19: {'weight': -1}},
   30: {20: {'weight': -1}},
   85: {29: {'weight': -1}, 49: {'weight': 1}},
   17: {31: {'weight': 1}},
   58: {67: {'weight': -1},
    63: {'weight': -1},
    49: {'weight': 1},
    52: {'weight': 1},
    70: {'weight': 1},
    62: {'weight': 3},
    65: {'weight': -1}},
   80: {40: {'weight': 1}},
   40: {57: {'weight': 1},
    78: {'weight': 1},
    49: {'weight': -1},
    2: {'weight': 1}},
   50: {82: {'weight': -1}, 1: {'weight': 1}},
   47: {50: {'weight': 1}},
   21: {50: {'weight': -1}},
   13: {20: {'weight': 1}},
   29: {22: {'weight': 1}, 24: {'weight': 1}},
   22: {77: {'weight': 1},
    3: {'weight': 1},
    76: {'weight': 1},
    65: {'weight': 1}},
   49: {21: {'weight': 1}},
   83: {31: {'weight': -1}, 52: {'weight': 1}},
   70: {7: {'weight': 1}, 49: {'weight': 1}, 78: {'weight': -1}},
   43: {36: {'weight': -1}, 52: {'weight': 1}},
   82: {47: {'weight': 1}, 61: {'weight': -1}, 1: {'weight': -1}},
   55: {34: {'weight': 1}, 72: {'weight': -1}},
   34: {74: {'weight': 1}, 61: {'weight': 1}},
   61: {60: {'weight': 1}, 18: {'weight': -1}},
   1: {34: {'weight': 1}},
   28: {15: {'weight': 1}},
   15: {20: {'weight': -1}},
   18: {19: {'weight': 1}},
   19: {14: {'weight': 1}},
   14: {52: {'weight': 1}},
   74: {52: {'weight': -1}, 57: {'weight': 1}},
   64: {37: {'weight': 1}, 77: {'weight': 1}},
   65: {62: {'weight': 1},
    23: {'weight': 1},
    81: {'weight': 3},
    58: {'weight': -1}},
   62: {65: {'weight': 1},
    55: {'weight': 1},
    2: {'weight': 1},
    16: {'weight': 3},
    38: {'weight': 3},
    39: {'weight': 3}},
   3: {23: {'weight': 1}, 69: {'weight': 1}},
   23: {3: {'weight': 1}},
   12: {60: {'weight': 1}},
   48: {60: {'weight': 1}, 47: {'weight': 1}},
   81: {48: {'weight': 1}, 11: {'weight': 1}},
   44: {62: {'weight': -1}},
   54: {62: {'weight': -1}},
   9: {62: {'weight': 1}},
   76: {35: {'weight': 1}},
   35: {41: {'weight': 3}, 55: {'weight': 1}},
   69: {62: {'weight': 1},
    58: {'weight': 3},
    74: {'weight': 1},
    16: {'weight': 3},
    38: {'weight': 3},
    51: {'weight': 3}},
   53: {55: {'weight': 1}},
   11: {60: {'weight': 1}, 10: {'weight': -1}},
   24: {26: {'weight': 1}},
   26: {27: {'weight': 1}, 65: {'weight': -1}},
   27: {65: {'weight': -1}},
   51: {16: {'weight': 3}},
   72: {69: {'weight': 1},
    76: {'weight': -1},
    73: {'weight': 1},
    55: {'weight': 1}},
   73: {69: {'weight': 1}},
   25: {26: {'weight': -1}}}],
 'Passages Clean_edited.json': [{1: 'accountability',
   2: 'alcohol exposed pregnancy',
   3: 'alcohol misuse',
   4: 'belief in a higher power',
   5: 'coping skills',
   6: 'death',
   7: 'dire situations',
   8: 'drug misuse',
   9: 'family emotional health',
   10: 'harmful romantic partners',
   11: 'healing',
   12: 'incarceration',
   13: 'intimate partner violence',
   14: 'losing family and children through justice or child welfare system involvement',
   15: 'mental health',
   16: 're-entry facility',
   17: 'resources that provide structure and support',
   18: 'supportive people'},
  {3: {13: {'weight': 1},
    9: {'weight': -1},
    7: {'weight': 1},
    15: {'weight': -1},
    12: {'weight': 1},
    2: {'weight': 1},
    8: {'weight': 1},
    14: {'weight': 1},
    18: {'weight': -1}},
   13: {3: {'weight': 1},
    10: {'weight': 1},
    7: {'weight': 1},
    15: {'weight': -1},
    12: {'weight': 1},
    6: {'weight': 1},
    8: {'weight': 1},
    14: {'weight': 1},
    18: {'weight': -1}},
   10: {13: {'weight': 1}},
   15: {3: {'weight': -1},
    13: {'weight': -1},
    5: {'weight': 1},
    4: {'weight': 1},
    18: {'weight': 1},
    11: {'weight': 1}},
   2: {12: {'weight': 1}, 14: {'weight': 1}, 15: {'weight': -1}},
   9: {15: {'weight': 1}},
   8: {3: {'weight': 1},
    13: {'weight': 1},
    4: {'weight': -1},
    12: {'weight': 1},
    15: {'weight': -1}},
   12: {4: {'weight': 1}},
   16: {4: {'weight': 1}, 17: {'weight': 1}, 18: {'weight': 1}},
   1: {16: {'weight': 1},
    15: {'weight': 1},
    5: {'weight': 1},
    11: {'weight': 1},
    4: {'weight': 1}},
   18: {15: {'weight': 1}, 11: {'weight': 1}, 1: {'weight': 1}},
   11: {15: {'weight': 1}, 4: {'weight': 1}, 18: {'weight': 1}},
   4: {16: {'weight': 1},
    5: {'weight': 1},
    1: {'weight': 1},
    10: {'weight': -1},
    3: {'weight': -1},
    8: {'weight': -1},
    15: {'weight': 1},
    11: {'weight': 1}},
   14: {15: {'weight': -1}},
   17: {1: {'weight': 1}, 11: {'weight': 1}},
   7: {16: {'weight': 1}}}],
 'Wavi combined clean_edited.json': [{1: 'adverse childhood experiences',
   2: 'alcohol misuse',
   3: 'approval of therapy',
   4: 'being self sufficient',
   5: 'child being abused in home',
   6: 'child welfare system intervention',
   7: 'children removed from house',
   8: 'children witness intimate partner violence',
   9: 'community acceptance of alcohol misuse',
   10: 'community acceptance of intimate partner violence',
   11: 'community alcohol misuse rate',
   12: 'community intimate partner violence rate',
   13: 'coping skills',
   14: 'couples therapy',
   15: 'court order',
   16: 'desire to stop family cycle of violence and alcohol misuse',
   17: 'family and friend permissive intimate partner violence norms',
   18: 'family functioning',
   19: 'healthy relationship functioning',
   20: 'healthy support system',
   21: 'intimate partner violence',
   22: 'isolation',
   23: 'knowledge about healthy relationships',
   24: 'leaving violent partner',
   25: 'legal troubles',
   26: 'mental health',
   27: 'mental health resources',
   28: 'negative treatment by child welfare case workers',
   29: 'partner power and control over person',
   30: 'partner willingness to change',
   31: 'personal strength',
   32: 'sober environments',
   33: 'stressful events',
   34: 'victimization stigma',
   35: 'wanting the violence by a partner or in a family to stop'},
  {2: {21: {'weight': 1},
    7: {'weight': 1},
    25: {'weight': 1},
    26: {'weight': -1},
    11: {'weight': 1}},
   21: {2: {'weight': 1},
    26: {'weight': -1},
    25: {'weight': 1},
    8: {'weight': 1},
    7: {'weight': 1},
    12: {'weight': 1},
    34: {'weight': 1},
    5: {'weight': 1},
    18: {'weight': -1},
    23: {'weight': -1},
    19: {'weight': -1}},
   26: {21: {'weight': -1},
    2: {'weight': -1},
    16: {'weight': 1},
    24: {'weight': 1}},
   31: {21: {'weight': 1}, 2: {'weight': -1}},
   16: {26: {'weight': 1},
    2: {'weight': -1},
    21: {'weight': -1},
    24: {'weight': 1},
    14: {'weight': 1}},
   27: {26: {'weight': 1}, 3: {'weight': 1}, 13: {'weight': 1}},
   15: {27: {'weight': 1}},
   25: {15: {'weight': 1}, 26: {'weight': -1}},
   6: {26: {'weight': -1},
    28: {'weight': 1},
    2: {'weight': 1},
    18: {'weight': 1}},
   7: {6: {'weight': 1}, 26: {'weight': -1}},
   28: {26: {'weight': -1}},
   3: {27: {'weight': 1}},
   11: {9: {'weight': 1}, 18: {'weight': -1}, 32: {'weight': -1}},
   10: {21: {'weight': 1}, 17: {'weight': 1}},
   8: {10: {'weight': 1}, 16: {'weight': 1}},
   18: {9: {'weight': -1},
    10: {'weight': -1},
    21: {'weight': -1},
    5: {'weight': -1}},
   33: {26: {'weight': -1}, 18: {'weight': -1}},
   30: {24: {'weight': -1}, 14: {'weight': 1}},
   24: {21: {'weight': -1}, 18: {'weight': 1}},
   14: {21: {'weight': -1}, 18: {'weight': -1}},
   32: {2: {'weight': -1}},
   9: {2: {'weight': 1}},
   12: {10: {'weight': 1}, 18: {'weight': 1}},
   34: {26: {'weight': -1}},
   4: {26: {'weight': 1}, 13: {'weight': 1}},
   5: {35: {'weight': 1}},
   35: {24: {'weight': 1}},
   17: {24: {'weight': -1}},
   23: {19: {'weight': 1}},
   1: {23: {'weight': -1}, 26: {'weight': -1}},
   20: {4: {'weight': 1}, 24: {'weight': 1}},
   19: {29: {'weight': -1}},
   29: {22: {'weight': 1}},
   22: {21: {'weight': 1}}}],
 'full circle clean_edited.json': [{1: 'ability to fulfill child welfare system requirements',
   2: 'accountability',
   3: 'adjustment during re-entry after incarceration',
   4: 'adverse childhood experiences',
   5: 'alcohol misuse',
   6: 'availability of child welfare system resources for family intervention',
   7: 'barriers to reunification with child in child welfare system',
   8: 'being drunk during intimate partner violence event',
   9: 'child welfare system intervention',
   10: 'childhood home functioning',
   11: 'children learning parenting skills',
   12: 'children living in home',
   13: 'children removed from house',
   14: 'children witness intimate partner violence',
   15: 'community acceptance of intimate partner violence',
   16: 'community discourse normalizing intimate partner violence',
   17: 'coping skills',
   18: 'death',
   19: 'desire for a romantic relationship',
   20: "desire to sacrifice self for children's safety against violent partner",
   21: 'desire to stop family cycle of violence and alcohol misuse',
   22: 'drug misuse',
   23: 'drug use during intimate partner violence event',
   24: 'efficacy of resources for promoting reunification',
   25: 'empowerment groups that are focused on indigenous culture',
   26: 'experience of systemic racism',
   27: 'experiencing indigenous culture',
   28: 'fear of children being taken by the child welfare system',
   29: 'fear of enabler retaliation',
   30: 'fear of getting arrested',
   31: 'fear of partner fighting for custody of children',
   32: 'fear of violent partner',
   33: 'generational trauma',
   34: 'getting child back from the child welfare system',
   35: 'healthy parenting practices',
   36: 'healthy relationship between children and parents',
   37: 'healthy support system',
   38: 'incarceration',
   39: 'indigenous cultural identity',
   40: 'intimate partner violence',
   41: 'learning intimate partner violence is acceptable as a child',
   42: 'leaving violent partner',
   43: 'loneliness in prison',
   44: 'mental health',
   45: 'number of people in jail',
   46: 'parents drinking in home',
   47: 'partner dependence',
   48: 'peer and or family enablers of violent partner',
   49: 'perceived protection from partner retaliation',
   50: 'perceptions of police as promoting safety',
   51: 'personal positive attitude towards the child welfare system',
   52: 'physical health',
   53: 'physical injury from intimate partner violence',
   54: 'police intervention',
   55: 'police racial bias and trauma sensitivity skills',
   56: 'positive community perception of the child welfare system',
   57: 'prison based mental health resource efficacy',
   58: 'prison mental health resource availability',
   59: 'prison mental health resource capacity',
   60: 'prison-based mental health resources received',
   61: 'quality of medical treatment received',
   62: 'quality of the parts of the relationship that are not violent',
   63: 'racism and or prejudice experienced by child welfare system workers',
   64: 'racism and or prejudice experienced by medical officials',
   65: 'racism and or prejudice experienced by police',
   66: 'received medical services',
   67: 'relationship functioning',
   68: 'relationship reunification with violent partner after prison',
   69: 'reporting partner violence event to police',
   70: 'resources received from the child welfare system',
   71: 'risk behavior education',
   72: 'seeking medical attention',
   73: 'self-worthlessness',
   74: 'stigma of being a bad parent',
   75: 'stigma of being a victim and being seen as weak',
   76: 'stigma of mental illness',
   77: 'using violence in self-defense from violent partner'},
  {40: {32: {'weight': 1},
    69: {'weight': 1},
    67: {'weight': -1},
    37: {'weight': -1},
    5: {'weight': 1},
    18: {'weight': 1},
    77: {'weight': 1},
    22: {'weight': 1},
    14: {'weight': 1},
    75: {'weight': 1},
    53: {'weight': 1},
    21: {'weight': 1}},
   55: {69: {'weight': 1}, 65: {'weight': -1}, 50: {'weight': 1}},
   47: {69: {'weight': -1},
    37: {'weight': -1},
    73: {'weight': 1},
    42: {'weight': -1}},
   32: {69: {'weight': -1}, 49: {'weight': -1}},
   67: {40: {'weight': -1}, 37: {'weight': 1}},
   37: {67: {'weight': 1},
    47: {'weight': -1},
    69: {'weight': 1},
    40: {'weight': -1},
    2: {'weight': 3},
    44: {'weight': 1},
    73: {'weight': -1},
    49: {'weight': 1}},
   5: {40: {'weight': 1},
    22: {'weight': 1},
    18: {'weight': 1},
    44: {'weight': -1},
    8: {'weight': 1},
    13: {'weight': 1},
    46: {'weight': 1},
    21: {'weight': 1}},
   22: {5: {'weight': 1},
    44: {'weight': -1},
    18: {'weight': 1},
    40: {'weight': 3},
    23: {'weight': 1},
    13: {'weight': 1}},
   10: {5: {'weight': -1},
    40: {'weight': -1},
    37: {'weight': 1},
    4: {'weight': -1},
    36: {'weight': 1},
    22: {'weight': -1}},
   44: {22: {'weight': -1},
    5: {'weight': -1},
    17: {'weight': 1},
    1: {'weight': 1},
    73: {'weight': -1},
    76: {'weight': -1}},
   17: {44: {'weight': 1},
    2: {'weight': 1},
    22: {'weight': 3},
    5: {'weight': 3}},
   2: {17: {'weight': 1}, 69: {'weight': 1}, 5: {'weight': -1}},
   33: {10: {'weight': -1}, 27: {'weight': -1}},
   27: {10: {'weight': 1}, 39: {'weight': 1}},
   39: {10: {'weight': 1}, 73: {'weight': -1}, 44: {'weight': 1}},
   25: {39: {'weight': 1}, 37: {'weight': 1}, 71: {'weight': 1}},
   35: {4: {'weight': -1},
    10: {'weight': 1},
    36: {'weight': 1},
    71: {'weight': 1}},
   77: {30: {'weight': 1}},
   30: {69: {'weight': -1}},
   8: {30: {'weight': 1}},
   28: {69: {'weight': 3}, 30: {'weight': 1}},
   4: {11: {'weight': -1}},
   11: {35: {'weight': 1}},
   12: {28: {'weight': 1}, 10: {'weight': 1}, 14: {'weight': 1}},
   36: {11: {'weight': 1}},
   23: {30: {'weight': 1}},
   14: {41: {'weight': 1},
    9: {'weight': 3},
    10: {'weight': -1},

# save all variables to an excel sheet

In [ ]:
# create a excel sheet where the nodes are listed in column 1 and the cld that comes from is listed in column 2 

# vars_G1 = list(list_of_G[0].nodes)

# print(vars_G1)

# df_vars = pd.DataFrame(vars_G1, columns = ['Variable'])
# df_vars['CLD'] = "Passage"


# df_vars.to_excel('var_names.xlsx', sheet_name='passage', index=False)

In [ ]:
# try:
#     writer = pd.ExcelWriter('output.xlsx', engine='xlsxwriter')
#     df1.to_excel(writer, sheet_name='Sheet1', index=False)
#     df2.to_excel(writer, sheet_name='Sheet2', index=False)
#     df3.to_excel(writer, sheet_name='Sheet3', index=False)
#     writer.close()
# except Exception as e:
#     print(f"An error occurred: {e}")

# Cleaning Vairable Names

## Clean the format of the vairable names

In [ ]:

# # clean variable format 
# i = 0
# variable_clean_dict = {}
# for k, v in cld_data.items():
#     for key, value in v[0].items():
        
#         correct_value = cld_nx.clean_variable_name(value)
#         if value != correct_value: 
#             variable_clean_dict[value]= correct_value
#             i += 1

#         v[0][key] = correct_value    
        


# print('---')
# print("Number of variables that corrected due to formating issue :", i)

In [ ]:
# with open("2_clean_format_dictionary.txt", "w") as fp:
#     json.dump(variable_clean_dict, fp)

In [ ]:
# write dictionary to a excel sheet, 
# with the original variable name and the corrected variable name
# df_1 = pd.DataFrame(variable_clean_dict.items(), columns=['Original', 'Corrected'])

## Spell Checking

In [ ]:

# custom_words = ['american indian and alaska native', 
#             'indian', 
#             'alaska',
#             'christianity', 
#             'fostercare', 
#             'american',
#             'child-rearing',
#             'reoffending', 
#             'lakota',
#             'mitakuye oyasin', 
#             'pushback',
#             'prosocial']

In [19]:
from spellchecker import SpellChecker

def correct_spelling(text, custom_words = []):
    spell = SpellChecker()
    spell.word_frequency.load_words(custom_words)
    
    words = text.split()
    corrected_words = [spell.correction(word) or word for word in words]
    return " ".join(corrected_words)

In [ ]:
# i = 0
# variable_correct_spell = {}
# for k, v in my_data.items():
#     for key, value in v[0].items():
#         corrected_text = correct_spelling(value, custom_words)
#         if value != corrected_text: 
#             variable_correct_spell[value] = corrected_text
#             # print(f'Original: {value}')
#             # print(f'Corrected: {corrected_text}')
#             i += 1
        
#         v[0][key] = corrected_text    
# print('---')
# print("Number of variables found needed spell check:", i)

In [ ]:
# variable_correct_spell

In [ ]:
# with open("3_spell_check_dictionary.txt", "w") as fp:
#     json.dump(variable_correct_spell, fp)

In [ ]:
# df_2 = pd.DataFrame(variable_correct_spell.items(), columns=['Original', 'Corrected'])

In [ ]:

# with pd.ExcelWriter('results/SYNCH/file_rename/RC_variables_matching060424.xlsx') as writer:
# # Adding dataframes to Excel as new sheets
#     df_1.to_excel(writer, sheet_name='1.clean format', index=False)
#     df_2.to_excel(writer, sheet_name='2.spellcheck', index=False)

# Find semantic similary variable names using pretrained sentence transformer

In [ ]:
# variable_clean_dict = {}
# for k, v in cld_data.items():
#     for key, value in v[0].items():
        
#         correct_value = clean_variable_name(value)
#         if value != correct_value: 
#             variable_clean_dict[value]= correct_value
#             i += 1

#         v[0][key] = correct_value

## Variable names

In [ ]:
# variable_names = []

# for k, v in cld_data.items():
#     cld_new_vars_name = []
#     cld_var_names = list(v[0].values())

#     variable_names.extend(cld_var_names)


# print("number of originial nodes: ", len(variable_names))

# variable_names = np.sort(list(set(variable_names)))
# print("number of originial unique nodes: ", len(variable_names))

In [ ]:
# print the first 10 words of variable names
# print(variable_names[:10])

## Sentence defintion names

In [20]:
variable_names = []

for k, v in dict_def.items():
    cld_new_vars_name = []
    cld_var_names = list(v.keys())

    variable_names.extend(cld_var_names)

print(variable_names[:10])
print("number of originial nodes: ", len(variable_names))

variable_names = np.sort(list(set(variable_names)))
print("number of originial unique nodes: ", len(variable_names))

["Adverse childhood experiences - can include child abuse or neglect, but more broadly also includes general lack of stability, safety, and healthy upbriniging in one's home, as well as exposures to chronic stressors and overall family maladjustment ", 'using alcohol - in reference to misuse', 'positive norms for alcohol use/misuse - percieved acceptability within the community/social circles', 'using alcohol while pregnant', "the accuracy of a caseworker's assessment of cllient needs", "Being held responsible for one's actions by others", "individuals' ability to receive a resource that is required for fufilling DSS obligations", 'availability of family members with whom a child taken into DSS custody can be placed with', "the extent to which an attourney understands both DSS and their clients' needs", 'the extent to which the attourney percieves that they should comply / work with DSS']
number of originial nodes:  213
number of originial unique nodes:  181

In [21]:
# Load a pretrained Sentence Transformer model
model = SentenceTransformer("all-mpnet-base-v2")

embeddings = model.encode(variable_names)

similarities = model.similarity(embeddings, embeddings)

/Users/gl665/PycharmProjects/Phrame_MentalMaps/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [57]:
# Output the pairs with their score
# for idx_i, sentence1 in enumerate(variable_names):
#     print(sentence1)
#     for idx_j, sentence2 in enumerate(variable_names):
#         if similarities[idx_i][idx_j] > 0.75:
#             print(f" - {sentence2: <30}: {similarities[idx_i][idx_j]:.4f}")
#             break

In [22]:
# flatten the dictionary by deleting the key 
flat_dict_def = {}
for key, value in dict_def.items():
    flat_dict_def.update(value)

In [23]:
# Group semantically similar names
groups = []
visited = set()

threshold = 0.75
for idx, name in enumerate(variable_names):
    if name not in visited:
        similar_names = [name]
        for jdx, similarity in enumerate(similarities[idx]):
            if jdx != idx and similarity >= threshold and variable_names[jdx] not in visited:
                similar_names.append(variable_names[jdx])
                visited.add(variable_names[jdx])
                
        groups.append(similar_names)
        visited.update(similar_names)

In [24]:
print("numbers of final variables after grouping: ", len(groups))
print("number of variables reduced: ", len(variable_names)- len(groups))

numbers of final variables after grouping:  155
number of variables reduced:  26

In [25]:
df_merge_groups = pd.DataFrame(groups)

columns = ['definition_{}'.format(i+1) for i in range(df_merge_groups.shape[1])]
df_merge_groups.columns = columns

for col in [col for col in df_merge_groups.columns if 'definition' in col]:
    df_merge_groups[f'variable_{col.split("_")[-1]}'] = df_merge_groups[col].map(flat_dict_def)


# sort based on the number of columns that are not nan 
df_merge_groups = df_merge_groups.reindex(df_merge_groups.count(axis=1).sort_values(ascending=False).index)

In [26]:
df_merge_groups.head()

,definition_1,definition_2,definition_3,variable_1,variable_2,variable_3
124,the amount of mental health resources availabl...,the amount of people that are able to receive ...,the extent to which individuals actively engag...,prison mental health resource availability,prison mental health resource capacity,prison-based mental health resources received
68,ending a relationship with a violent partner,leaving a violent partner,leaving a violent partner/ending a relationshi...,ending violent relationship,separation from violent partner,leaving violent partner
42,actively looking for resources to address ment...,resources to help with mental health needs e.g...,the quality / extent to which mental health re...,mental health resource seeking,mental health resources,prison based mental health resource efficacy
29,The extent to which alcohol misuse is accepted...,The rate of alcohol misuse within the community,positive norms for alcohol use/misuse - percie...,community acceptance of alcohol misuse,community alcohol misuse rate,alcohol use norms
6,Both professional and non-professional individ...,informal (family/friends/mentors) and formal i...,None,supportive people,healthy support system,NaN

In [27]:
# save groups to excel sheet
file_path = str(parent_dir / 'results/SYNCH/JSON_file/RC/results sheets/data_dictionary/grouping/SYNCH_grouping_by_definition.xlsx')
# df_merge_groups.to_excel(file_path, sheet_name='threshold_0.65', index=False)

In [28]:
if not os.path.exists(file_path):   
    with pd.ExcelWriter(file_path, mode='w', engine='openpyxl') as writer:
        df_merge_groups.to_excel(writer, index=False, sheet_name='tr_0.75(full,passage,wavi,dss)')
else:   
    with pd.ExcelWriter(file_path, mode='a', engine='openpyxl', if_sheet_exists= "replace") as writer:
        df_merge_groups.to_excel(writer, index=False, sheet_name='tr_0.75(full,passage,wavi,dss)')

In [29]:
df_merge_groups.head()

,definition_1,definition_2,definition_3,variable_1,variable_2,variable_3
124,the amount of mental health resources availabl...,the amount of people that are able to receive ...,the extent to which individuals actively engag...,prison mental health resource availability,prison mental health resource capacity,prison-based mental health resources received
68,ending a relationship with a violent partner,leaving a violent partner,leaving a violent partner/ending a relationshi...,ending violent relationship,separation from violent partner,leaving violent partner
42,actively looking for resources to address ment...,resources to help with mental health needs e.g...,the quality / extent to which mental health re...,mental health resource seeking,mental health resources,prison based mental health resource efficacy
29,The extent to which alcohol misuse is accepted...,The rate of alcohol misuse within the community,positive norms for alcohol use/misuse - percie...,community acceptance of alcohol misuse,community alcohol misuse rate,alcohol use norms
6,Both professional and non-professional individ...,informal (family/friends/mentors) and formal i...,None,supportive people,healthy support system,NaN

In [77]:
# df_merge_groups.iloc[1, 1]

'perpetration/victimization of violence by a or to a romantic partner through physical, sexual, mental/psychological, financial, social means'

In [89]:

# Print grouped variable names

for i, group in enumerate(groups):
    if len(group) > 1:
        print(f"Group {i + 1}: {group}")

len(groups)

Group 1: mental health
Group 2: isolation
Group 3: adverse childhood experiences
Group 4: accountability
Group 5: supportive people
Group 6: partner power and control over person
Group 7: child being abused in home
Group 8: couple's therapy
Group 9: resources that provide structure and support
Group 10: child welfare system intervention
Group 11: court order
Group 12: dire situations
Group 13: family functioning
Group 14: approval of therapy
Group 15: belief in a higher power
Group 16: negative treatment by child welfare case workers
Group 17: harmful romantic partners
Group 18: coping skills
Group 19: community acceptance of alcohol misuse
Group 20: community acceptance of intimate partner violence
Group 21: family emotional health
Group 22: community alcohol misuse rate
Group 23: community intimate partner violence rate
Group 24: re-entry facility
Group 25: incarceration
Group 26: stressful events
Group 27: children witness intimate partner violence
Group 28: death
Group 29: family and friend permissive intimate partner violence norms
Group 30: knowledge about healthy relationships
Group 31: healthy support system
Group 32: victimization stigma
Group 33: legal troubles
Group 34: leaving violent partner
Group 35: children removed from house
Group 36: desire to stop family cycle of violence and alcohol misuse
Group 37: intimate partner violence
Group 38: mental health resources
Group 39: being self sufficient
Group 40: sober environments
Group 41: partner willingness to change
Group 42: healthy relationship functioning
Group 43: alcohol misuse
Group 44: drug misuse
Group 45: wanting the violence by a partner or in a family to stop
Group 46: personal strength

46

In [51]:
# create a dictionary to swap the words that are bundled in the group. 
swap_dict = {}

for group in groups:
    if len(group) > 1:
        longest_name = max(group, key=len)
        swap_dict[longest_name] = group
swap_dict

swap_dict_reversed = {v: k for k, vv in swap_dict.items() for v in vv}
swap_dict_reversed

{'A lack of social interaction/social support from others - typically in reference to losing friends or family as a consequence of being with a violent partner (who "cuts off" a victim from others)': 'A lack of social interaction/social support from others - typically in reference to losing friends or family as a consequence of being with a violent partner (who "cuts off" a victim from others)',
 'perpetration/victimization of violence by a or to a romantic partner through physical, sexual, mental/psychological, financial, social means': 'A lack of social interaction/social support from others - typically in reference to losing friends or family as a consequence of being with a violent partner (who "cuts off" a victim from others)',
 "Adverse childhood experiences - can include child abuse or neglect, but more broadly also includes general lack of stability, safety, and healthy upbriniging in one's home, as well as exposures to chronic stressors and overall family maladjustment ": "Adverse childhood experiences - can include child abuse or neglect, but more broadly also includes general lack of stability, safety, and healthy upbriniging in one's home, as well as exposures to chronic stressors and overall family maladjustment ",
 'any experience (typically related to environments one is in/ traumatic experiences) that triggers stress ': "Adverse childhood experiences - can include child abuse or neglect, but more broadly also includes general lack of stability, safety, and healthy upbriniging in one's home, as well as exposures to chronic stressors and overall family maladjustment ",
 'Both professional and non-professional individuals (but in this case mostly professional or within a professional/setting) who provide you with emotional and possibly practical support': 'Both professional and non-professional individuals (but in this case mostly professional or within a professional/setting) who provide you with emotional and possibly practical support',
 'informal (family/friends/mentors) and formal individuals who offer emotional or practical support - as well as those who can advocate and stand up for individuals when victimized': 'Both professional and non-professional individuals (but in this case mostly professional or within a professional/setting) who provide you with emotional and possibly practical support',
 "From the perspective of the parent - observing one's child abused by others (typically by a partner) or abusing a child oneself": 'family members or friends who enable an abusive partner (either delliberate, such as retaliating against victims who call the police, or complicitly, through staying silient and giving covert approval)',
 "children witnessing violence between one's parent(s) ": 'family members or friends who enable an abusive partner (either delliberate, such as retaliating against victims who call the police, or complicitly, through staying silient and giving covert approval)',
 'family members or friends who enable an abusive partner (either delliberate, such as retaliating against victims who call the police, or complicitly, through staying silient and giving covert approval)': 'family members or friends who enable an abusive partner (either delliberate, such as retaliating against victims who call the police, or complicitly, through staying silient and giving covert approval)',
 'Intervention by child welfare/child protective services due to endangement of a child': 'Intervention by child welfare/child protective services due to endangement of a child',
 'Quality of the way that individuals are treated by child welfare caseworkers': 'Intervention by child welfare/child protective services due to endangement of a child',
 'Overall familial health through healthy interpersonal interaction, family stability, safety, and cohesiveness - taken from the perspective of an adult family member': 'Overall familial health through healthy interpersonal interaction, family stability, safety, and cohesiveness - taken from the perspective of an adult family member',
 'The mental/emotional health  of the family. Could refer to family raised in (as child) or family as an adult (e.g., with spouse and child). ': 'Overall familial health through healthy interpersonal interaction, family stability, safety, and cohesiveness - taken from the perspective of an adult family member',
 'Strategies and ability to carry out strategies related to dealling with internal and external negative experiences, broadly related to behavioral and emotional/mental regulation and resiliency': 'Strategies and ability to carry out strategies related to dealling with internal and external negative experiences, broadly related to behavioral and emotional/mental regulation and resiliency',
 "willpower, perseverence, related to the ability to change ones' behavior or situations, or to endure stress": 'Strategies and ability to carry out strategies related to dealling with internal and external negative experiences, broadly related to behavioral and emotional/mental regulation and resiliency',
 'The extent to which alcohol misuse is accepted in the community - alcohol misuse norms (permissive/positive)': 'The extent to which alcohol misuse is accepted in the community - alcohol misuse norms (permissive/positive)',
 'The rate of alcohol misuse within the community': 'The extent to which alcohol misuse is accepted in the community - alcohol misuse norms (permissive/positive)',
 'The extent to which intimate partner violence is accepted in the community - intimate partner violence norms (positive/permissive) - can also be considered the extent to which intimate partner violence is seen as an acceptable solution to conflict resolution': 'The extent to which intimate partner violence is accepted in the community - intimate partner violence norms (positive/permissive) - can also be considered the extent to which intimate partner violence is seen as an acceptable solution to conflict resolution',
 'The rate of intimate partner violence within the community': 'The extent to which intimate partner violence is accepted in the community - intimate partner violence norms (positive/permissive) - can also be considered the extent to which intimate partner violence is seen as an acceptable solution to conflict resolution',
 'the extent to which a partner is ammenable to, or actively desires to, change their behaviors / the way they interact with their partner/ to improve the relationship and reduce intimate partner violence within the relationship': 'The extent to which intimate partner violence is accepted in the community - intimate partner violence norms (positive/permissive) - can also be considered the extent to which intimate partner violence is seen as an acceptable solution to conflict resolution',
 'having a healthy internal working model - e.g., what a healthy partner "looks like", how one should be treated by their partner and how they should treat their partner in a healthy, nonviolent, and loving way': 'having a healthy internal working model - e.g., what a healthy partner "looks like", how one should be treated by their partner and how they should treat their partner in a healthy, nonviolent, and loving way',
 'the interpersonal health of a romantic relationship - e.g., communication, boundaries, cooperation, support, conflict resolution': 'having a healthy internal working model - e.g., what a healthy partner "looks like", how one should be treated by their partner and how they should treat their partner in a healthy, nonviolent, and loving way',
 'using alcohol - in reference to misuse': 'using alcohol - in reference to misuse',
 'using drugs -in reference to misuse': 'using alcohol - in reference to misuse'}

In [39]:
len(swap_dict_reversed)

4

In [40]:
# Swap the variable names in the data

cld_data_new = cld_data.copy()

for k, v in cld_data_new.items():
    for key, value in v[0].items():
        if value in swap_dict_reversed:
            v[0][key] = swap_dict_reversed[value]

In [41]:
variable_names = [list(v[0].values()) for k, v in cld_data_new.items()]

variable_names = sum(variable_names, [])

variable_names = np.sort(list(set(variable_names)))


print("number of originial unique nodes after cleaning the data: ", len(variable_names))

number of originial unique nodes after cleaning the data:  49

# write out the cleaned data to pickle

In [ ]:
# # Specify the file path where you want to save the pickled data
file_path = "results/SYNCH/JSON_file/RC_cld_data_cleaned_and_merged.json"

merged_file_path = str(parent_dir / file_path)

# Pickle dump the cld_data_new dictionary
with open(merged_file_path, "wb") as file:
    pickle.dump(cld_data_new, file)

c:\Users\GL665\Documents\Phrame-MentalMaps\results\SYNCH\JSON_file\RC_cld_data_cleaned_and_merged.json