
# Cleaning Dataset 

Perform data cleaning on the SYNCH Rapid City Dataset, including formating the variable names, spell checking.

In [55]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Import library

In [56]:

from sentence_transformers import SentenceTransformer, util , SimilarityFunction
from pathlib import Path


import pandas as pd
import numpy as np
import regex as re
import itertools as it
import matplotlib.pyplot as plt
import pickle
import os
import torch
import seaborn as sns 
import sys
import json
import networkx as nx

In [57]:

# Get the current working directory
cwd = Path.cwd()

# Get the path to the parent directory
parent_dir = cwd.parent

# Add the parent directory to the Python path
sys.path.append(str(parent_dir))

# Now you can import the data_io module from src
import src.data_io as data_io
import src.cld_nx as cld_nx

# Read data

In [58]:
print(os.getcwd())

/Users/gl665/PycharmProjects/Phrame_MentalMaps/notebook

## Read Raw data

In [11]:
# Go one level up from the current directory
# cwd = os.getcwd()

# parent_dir = Path(cwd).parent
# print(parent_dir)

# my_data_RC = {}
# folder_path = str(parent_dir / 'results/SYNCH/JSON_file/RC/')


# cld_data = data_io.read_json(folder_path, my_data_RC)

## Read clean data

In [59]:
cwd = os.getcwd()

parent_dir = Path(cwd).parent
print(parent_dir)

my_data = {}
folder_path = str(parent_dir / 'results/SYNCH/JSON_file/RC/clean')


cld_data = data_io.read_json(folder_path, my_data)

/Users/gl665/PycharmProjects/Phrame_MentalMaps
load: Passages Clean_edited.json
load: Wavi combined clean_edited.json

In [60]:
# dict_cld = {name_file: nxgraph}

dict_cld = {}

for k, v in my_data.items():
    cld_list, G_cld = cld_nx.get_cld_graph(my_data, k)
    # cld_name = dict_file_rename.get(k, "")
    dict_cld[k] = G_cld

list_of_G = list(dict_cld.values())

for k, v in dict_cld.items(): 
    print(k, ":", v)

Passages Clean_edited.json : DiGraph with 18 nodes and 61 edges
Wavi combined clean_edited.json : DiGraph with 35 nodes and 78 edges

## Read already preprocessed data

In [7]:
# read the data 
# file_path = "results/SYNCH/JSON_file/RC_cld_data_cleaned_preprocessed.json"

# # Pickle dump the cld_data_new dictionary
# with open(file_path, "rb") as file:
#     cld_data = pickle.load(file)

# print(cld_data)

# Read Variable dicitionary, variable name and definition

In [61]:
# results/SYNCH/JSON_file/RC/clean/Wavi combined clean_edited.json

# import json

cwd = os.getcwd()

parent_dir = Path(cwd).parent

dict_def = {}
file_path = str(parent_dir /'results/SYNCH/JSON_file/RC/results sheets/data_dictionary/')

for file in os.listdir(file_path):
    if file.endswith(".json"):
        with open(file_path + "/" + file, 'r') as f:
            data = json.load(f)
            dict_def[file] = data

# with open(file_path, 'rb') as f:
#     data = json.load(f)

In [62]:
dict_def.values()

dict_values([{"Being held responsible for one's actions by others": 'accountability', 'using alcohol - in reference to misuse': 'alcohol misuse', 'Strategies and ability to carry out strategies related to dealling with internal and external negative experiences, broadly related to behavioral and emotional/mental regulation and resiliency': 'coping skills', 'Long-term Situtations/experiences that cause extreme stress or trauma, facilitate substancial consequences, or otherwise require "survival"': 'dire situations', 'using drugs -in reference to misuse': 'drug misuse', 'death': 'death', 'The mental/emotional health  of the family. Could refer to family raised in (as child) or family as an adult (e.g., with spouse and child). ': 'family emotional health', 'legal suspension of parental custody - children being placed in the custody of others (e.g., other family members, foster homes, group homes)': 'losing family and children through justice or child welfare system involvement', 'Placing faith in a higher power for guidance, feeling security and love from a higher power ': 'belief in a higher power', 'an individual going to jail / prison due to being arrested and convicted of a crime': 'incarceration', 'perpetration/victimization of violence by a or to a romantic partner through physical, sexual, mental/psychological, financial, social means': 'intimate partner violence', '"Increases" in mental health indicate a decline in negative emotions/mental illness and a rise in positive emotionality': 'mental health', 'Romantic partners who are  harmful and many perpetuate IPV - those who typically have issues with emotions or behaviors themselves': 'harmful romantic partners', 'a halfway house for women who get out of prison': 're-entry facility', 'Both professional and non-professional individuals (but in this case mostly professional or within a professional/setting) who provide you with emotional and possibly practical support': 'supportive people', 'In reference to the specific halfway house participants were in - providing stability and structure in their daily lives within a supportive and nurturing environment': 'resources that provide structure and support'}, {"Adverse childhood experiences - can include child abuse or neglect, but more broadly also includes general lack of stability, safety, and healthy upbriniging in one's home, as well as exposures to chronic stressors and overall family maladjustment ": 'adverse childhood experiences', 'using alcohol - in reference to misuse': 'alcohol misuse', 'Percieved acceptability of therapy as a solution/form of help ': 'approval of therapy', "From the perspective of the parent - observing one's child abused by others (typically by a partner) or abusing a child oneself": 'child being abused in home', 'The rate of alcohol misuse within the community': 'community alcohol misuse rate', 'The extent to which alcohol misuse is accepted in the community - alcohol misuse norms (permissive/positive)': 'community acceptance of alcohol misuse', 'The extent to which intimate partner violence is accepted in the community - intimate partner violence norms (positive/permissive) - can also be considered the extent to which intimate partner violence is seen as an acceptable solution to conflict resolution': 'community acceptance of intimate partner violence', 'The rate of intimate partner violence within the community': 'community intimate partner violence rate ', 'Going to relationship therapy with partner': "couple's therapy", 'Strategies and ability to carry out strategies related to dealling with internal and external negative experiences, broadly related to behavioral and emotional/mental regulation and resiliency': 'coping skills', 'Legal mandate that is a requirement for resolving a legal issue (e.g., probation, DSS). Usually requires receiving and successfully completing treatment ,but also can be to secure housing, employment, etc.': 'court order', "observing the cycles of violence and/or substance use over generations within one's own family, and the desire to not to contribute to this cycle by perpetuating / experiencing more violence / substance use - typically in reference to a fear of transmission of this cycle to one's children": 'desire to stop family cycle of violence and alcohol misuse', 'Intervention by child welfare/child protective services due to endangement of a child': 'child welfare system intervention', 'Overall familial health through healthy interpersonal interaction, family stability, safety, and cohesiveness - taken from the perspective of an adult family member': 'family functioning', 'having a healthy internal working model - e.g., what a healthy partner "looks like", how one should be treated by their partner and how they should treat their partner in a healthy, nonviolent, and loving way': 'knowledge about healthy relationships', 'A lack of social interaction/social support from others - typically in reference to losing friends or family as a consequence of being with a violent partner (who "cuts off" a victim from others)': 'isolation', "children witnessing violence between one's parent(s) ": 'children witness intimate partner violence', 'legal suspension of parental custody - children being placed in the custody of others (e.g., other family members, foster homes, group homes)': 'children removed from house', 'perpetration/victimization of violence by a or to a romantic partner through physical, sexual, mental/psychological, financial, social means': 'intimate partner violence', 'leaving a violent partner/ending a relationship with a violent partner': 'leaving violent partner', '"Increases" in mental health indicate a decline in negative emotions/mental illness and a rise in positive emotionality': 'mental health', 'resources to help with mental health needs e.g., therapy': 'mental health resources', 'involvement with the justice system (e.g., getting arrested)': 'legal troubles', 'the extent to which a partner is ammenable to, or actively desires to, change their behaviors / the way they interact with their partner/ to improve the relationship and reduce intimate partner violence within the relationship': 'partner willingness to change', "willpower, perseverence, related to the ability to change ones' behavior or situations, or to endure stress": 'personal strength', 'family members or friends who enable an abusive partner (either delliberate, such as retaliating against victims who call the police, or complicitly, through staying silient and giving covert approval)': 'family and friend permissive intimate partner violence norms', "Domination and control over one's partner, through physical, emotional, financial, social, or other means": 'partner power and control over person', 'the interpersonal health of a romantic relationship - e.g., communication, boundaries, cooperation, support, conflict resolution': 'healthy relationship functioning', 'informal (family/friends/mentors) and formal individuals who offer emotional or practical support - as well as those who can advocate and stand up for individuals when victimized': 'healthy support system', 'the ability to support oneself by obtaining and meeting all needs (both basic and more intrinsic, such as mental health or emotional needs)': 'being self sufficient', 'any experience (typically related to environments one is in/ traumatic experiences) that triggers stress ': 'stressful events', 'the availability and accessibility of sober social circles, functions, and activities within the community - usually in reference to the extent to which alcohol plays a role in social environments': 'sober environments', 'Quality of the way that individuals are treated by child welfare caseworkers': 'negative treatment by child welfare case workers', 'wanting to stop being victimized within an intimate partner violence relationship': 'wanting the violence by a partner or in a family to stop', 'internal or external stigma experienced due to being victimized by a partner': 'victimization stigma'}])

# Single CLD view

In [63]:
cld_data

{'Passages Clean_edited.json': [{1: 'accountability',
   2: 'alcohol exposed pregnancy',
   3: 'alcohol misuse',
   4: 'belief in a higher power',
   5: 'coping skills',
   6: 'death',
   7: 'dire situations',
   8: 'drug misuse',
   9: 'family emotional health',
   10: 'harmful romantic partners',
   11: 'healing',
   12: 'incarceration',
   13: 'intimate partner violence',
   14: 'losing family and children through justice or child welfare system involvement',
   15: 'mental health',
   16: 're-entry facility',
   17: 'resources that provide structure and support',
   18: 'supportive people'},
  {3: {13: {'weight': 1},
    9: {'weight': -1},
    7: {'weight': 1},
    15: {'weight': -1},
    12: {'weight': 1},
    2: {'weight': 1},
    8: {'weight': 1},
    14: {'weight': 1},
    18: {'weight': -1}},
   13: {3: {'weight': 1},
    10: {'weight': 1},
    7: {'weight': 1},
    15: {'weight': -1},
    12: {'weight': 1},
    6: {'weight': 1},
    8: {'weight': 1},
    14: {'weight': 1},
    18: {'weight': -1}},
   10: {13: {'weight': 1}},
   15: {3: {'weight': -1},
    13: {'weight': -1},
    5: {'weight': 1},
    4: {'weight': 1},
    18: {'weight': 1},
    11: {'weight': 1}},
   2: {12: {'weight': 1}, 14: {'weight': 1}, 15: {'weight': -1}},
   9: {15: {'weight': 1}},
   8: {3: {'weight': 1},
    13: {'weight': 1},
    4: {'weight': -1},
    12: {'weight': 1},
    15: {'weight': -1}},
   12: {4: {'weight': 1}},
   16: {4: {'weight': 1}, 17: {'weight': 1}, 18: {'weight': 1}},
   1: {16: {'weight': 1},
    15: {'weight': 1},
    5: {'weight': 1},
    11: {'weight': 1},
    4: {'weight': 1}},
   18: {15: {'weight': 1}, 11: {'weight': 1}, 1: {'weight': 1}},
   11: {15: {'weight': 1}, 4: {'weight': 1}, 18: {'weight': 1}},
   4: {16: {'weight': 1},
    5: {'weight': 1},
    1: {'weight': 1},
    10: {'weight': -1},
    3: {'weight': -1},
    8: {'weight': -1},
    15: {'weight': 1},
    11: {'weight': 1}},
   14: {15: {'weight': -1}},
   17: {1: {'weight': 1}, 11: {'weight': 1}},
   7: {16: {'weight': 1}}}],
 'Wavi combined clean_edited.json': [{1: 'adverse childhood experiences',
   2: 'alcohol misuse',
   3: 'approval of therapy',
   4: 'being self sufficient',
   5: 'child being abused in home',
   6: 'child welfare system intervention',
   7: 'children removed from house',
   8: 'children witness intimate partner violence',
   9: 'community acceptance of alcohol misuse',
   10: 'community acceptance of intimate partner violence',
   11: 'community alcohol misuse rate',
   12: 'community intimate partner violence rate',
   13: 'coping skills',
   14: 'couples therapy',
   15: 'court order',
   16: 'desire to stop family cycle of violence and alcohol misuse',
   17: 'family and friend permissive intimate partner violence norms',
   18: 'family functioning',
   19: 'healthy relationship functioning',
   20: 'healthy support system',
   21: 'intimate partner violence',
   22: 'isolation',
   23: 'knowledge about healthy relationships',
   24: 'leaving violent partner',
   25: 'legal troubles',
   26: 'mental health',
   27: 'mental health resources',
   28: 'negative treatment by child welfare case workers',
   29: 'partner power and control over person',
   30: 'partner willingness to change',
   31: 'personal strength',
   32: 'sober environments',
   33: 'stressful events',
   34: 'victimization stigma',
   35: 'wanting the violence by a partner or in a family to stop'},
  {2: {21: {'weight': 1},
    7: {'weight': 1},
    25: {'weight': 1},
    26: {'weight': -1},
    11: {'weight': 1}},
   21: {2: {'weight': 1},
    26: {'weight': -1},
    25: {'weight': 1},
    8: {'weight': 1},
    7: {'weight': 1},
    12: {'weight': 1},
    34: {'weight': 1},
    5: {'weight': 1},
    18: {'weight': -1},
    23: {'weight': -1},
    19: {'weight': -1}},
   26: {21: {'weight': -1},
    2: {'weight': -1},
    16: {'weight': 1},
    24: {'weight': 1}},
   31: {21: {'weight': 1}, 2: {'weight': -1}},
   16: {26: {'weight': 1},
    2: {'weight': -1},
    21: {'weight': -1},
    24: {'weight': 1},
    14: {'weight': 1}},
   27: {26: {'weight': 1}, 3: {'weight': 1}, 13: {'weight': 1}},
   15: {27: {'weight': 1}},
   25: {15: {'weight': 1}, 26: {'weight': -1}},
   6: {26: {'weight': -1},
    28: {'weight': 1},
    2: {'weight': 1},
    18: {'weight': 1}},
   7: {6: {'weight': 1}, 26: {'weight': -1}},
   28: {26: {'weight': -1}},
   3: {27: {'weight': 1}},
   11: {9: {'weight': 1}, 18: {'weight': -1}, 32: {'weight': -1}},
   10: {21: {'weight': 1}, 17: {'weight': 1}},
   8: {10: {'weight': 1}, 16: {'weight': 1}},
   18: {9: {'weight': -1},
    10: {'weight': -1},
    21: {'weight': -1},
    5: {'weight': -1}},
   33: {26: {'weight': -1}, 18: {'weight': -1}},
   30: {24: {'weight': -1}, 14: {'weight': 1}},
   24: {21: {'weight': -1}, 18: {'weight': 1}},
   14: {21: {'weight': -1}, 18: {'weight': -1}},
   32: {2: {'weight': -1}},
   9: {2: {'weight': 1}},
   12: {10: {'weight': 1}, 18: {'weight': 1}},
   34: {26: {'weight': -1}},
   4: {26: {'weight': 1}, 13: {'weight': 1}},
   5: {35: {'weight': 1}},
   35: {24: {'weight': 1}},
   17: {24: {'weight': -1}},
   23: {19: {'weight': 1}},
   1: {23: {'weight': -1}, 26: {'weight': -1}},
   20: {4: {'weight': 1}, 24: {'weight': 1}},
   19: {29: {'weight': -1}},
   29: {22: {'weight': 1}},
   22: {21: {'weight': 1}}}]}

# save all variables to an excel sheet

In [ ]:
# create a excel sheet where the nodes are listed in column 1 and the cld that comes from is listed in column 2 

# vars_G1 = list(list_of_G[0].nodes)

# print(vars_G1)

# df_vars = pd.DataFrame(vars_G1, columns = ['Variable'])
# df_vars['CLD'] = "Passage"


# df_vars.to_excel('var_names.xlsx', sheet_name='passage', index=False)

In [ ]:
# try:
#     writer = pd.ExcelWriter('output.xlsx', engine='xlsxwriter')
#     df1.to_excel(writer, sheet_name='Sheet1', index=False)
#     df2.to_excel(writer, sheet_name='Sheet2', index=False)
#     df3.to_excel(writer, sheet_name='Sheet3', index=False)
#     writer.close()
# except Exception as e:
#     print(f"An error occurred: {e}")

# Cleaning Vairable Names

## Clean the format of the vairable names

In [64]:

# clean variable format 
i = 0
variable_clean_dict = {}
for k, v in cld_data.items():
    for key, value in v[0].items():
        
        correct_value = cld_nx.clean_variable_name(value)
        if value != correct_value: 
            variable_clean_dict[value]= correct_value
            i += 1

        v[0][key] = correct_value    
        


print('---')
print("Number of variables that corrected due to formating issue :", i)

---
Number of variables that corrected due to formating issue : 0

In [9]:
# with open("2_clean_format_dictionary.txt", "w") as fp:
#     json.dump(variable_clean_dict, fp)

In [20]:
# write dictionary to a excel sheet, 
# with the original variable name and the corrected variable name
# df_1 = pd.DataFrame(variable_clean_dict.items(), columns=['Original', 'Corrected'])

## Spell Checking

In [65]:
# TODO: Q: Need to refine these 

custom_words = ['american indian and alaska native', 
            'indian', 
            'alaska',
            'christianity', 
            'fostercare', 
            'american',
            'child-rearing',
            'reoffending', 
            'lakota',
            'mitakuye oyasin', 
            'pushback',
            'prosocial']

In [66]:
from spellchecker import SpellChecker

def correct_spelling(text, custom_words = []):
    spell = SpellChecker()
    spell.word_frequency.load_words(custom_words)
    
    words = text.split()
    corrected_words = [spell.correction(word) or word for word in words]
    return " ".join(corrected_words)

In [67]:
i = 0
variable_correct_spell = {}
for k, v in my_data.items():
    for key, value in v[0].items():
        corrected_text = correct_spelling(value, custom_words)
        if value != corrected_text: 
            variable_correct_spell[value] = corrected_text
            # print(f'Original: {value}')
            # print(f'Corrected: {corrected_text}')
            i += 1
        
        v[0][key] = corrected_text    
print('---')
print("Number of variables found needed spell check:", i)

---
Number of variables found needed spell check: 1

In [68]:
variable_correct_spell

{'re-entry facility': 'reentry facility'}

In [8]:
# with open("3_spell_check_dictionary.txt", "w") as fp:
#     json.dump(variable_correct_spell, fp)

In [25]:
# df_2 = pd.DataFrame(variable_correct_spell.items(), columns=['Original', 'Corrected'])

In [ ]:

# with pd.ExcelWriter('results/SYNCH/file_rename/RC_variables_matching060424.xlsx') as writer:
# # Adding dataframes to Excel as new sheets
#     df_1.to_excel(writer, sheet_name='1.clean format', index=False)
#     df_2.to_excel(writer, sheet_name='2.spellcheck', index=False)

# Find semantic similary variable names using pretrained sentence transformer

In [ ]:
# variable_clean_dict = {}
# for k, v in cld_data.items():
#     for key, value in v[0].items():
        
#         correct_value = clean_variable_name(value)
#         if value != correct_value: 
#             variable_clean_dict[value]= correct_value
#             i += 1

#         v[0][key] = correct_value

## Variable names

In [ ]:
# variable_names = []

# for k, v in cld_data.items():
#     cld_new_vars_name = []
#     cld_var_names = list(v[0].values())

#     variable_names.extend(cld_var_names)


# print("number of originial nodes: ", len(variable_names))

# variable_names = np.sort(list(set(variable_names)))
# print("number of originial unique nodes: ", len(variable_names))

In [ ]:
# print the first 10 words of variable names
# print(variable_names[:10])

## Sentence defintion names

In [69]:
variable_names = []

for k, v in dict_def.items():
    cld_new_vars_name = []
    cld_var_names = list(v.keys())

    variable_names.extend(cld_var_names)

print(variable_names[:10])
print("number of originial nodes: ", len(variable_names))

variable_names = np.sort(list(set(variable_names)))
print("number of originial unique nodes: ", len(variable_names))

["Being held responsible for one's actions by others", 'using alcohol - in reference to misuse', 'Strategies and ability to carry out strategies related to dealling with internal and external negative experiences, broadly related to behavioral and emotional/mental regulation and resiliency', 'Long-term Situtations/experiences that cause extreme stress or trauma, facilitate substancial consequences, or otherwise require "survival"', 'using drugs -in reference to misuse', 'death', 'The mental/emotional health  of the family. Could refer to family raised in (as child) or family as an adult (e.g., with spouse and child). ', 'legal suspension of parental custody - children being placed in the custody of others (e.g., other family members, foster homes, group homes)', 'Placing faith in a higher power for guidance, feeling security and love from a higher power ', 'an individual going to jail / prison due to being arrested and convicted of a crime']
number of originial nodes:  51
number of originial unique nodes:  46

In [70]:
# Load a pretrained Sentence Transformer model
model = SentenceTransformer("all-mpnet-base-v2")

embeddings = model.encode(variable_names)

similarities = model.similarity(embeddings, embeddings)

/Users/gl665/PycharmProjects/Phrame_MentalMaps/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [ ]:
# Output the pairs with their score
# for idx_i, sentence1 in enumerate(variable_names):
#     print(sentence1)
#     for idx_j, sentence2 in enumerate(variable_names):
#         if similarities[idx_i][idx_j] > 0.75:
#             print(f" - {sentence2: <30}: {similarities[idx_i][idx_j]:.4f}")
#             break

In [110]:
# flatten the dictionary by deleting the key 
flat_dict_def = {}
for key, value in dict_def.items():
    flat_dict_def.update(value)

In [131]:
# Group semantically similar names
groups = []
visited = set()

threshold = 0.75
for idx, name in enumerate(variable_names):
    if name not in visited:
        similar_names = [name]
        for jdx, similarity in enumerate(similarities[idx]):
            if jdx != idx and similarity >= threshold and variable_names[jdx] not in visited:
                similar_names.append(variable_names[jdx])
                visited.add(variable_names[jdx])
                
        groups.append(similar_names)
        visited.update(similar_names)

In [132]:
print("numbers of final variables after grouping: ", len(groups))
print("number of variables reduced: ", len(variable_names)- len(groups))

numbers of final variables after grouping:  44
number of variables reduced:  2

In [133]:
df_merge_groups = pd.DataFrame(groups)

columns = ['definition_{}'.format(i+1) for i in range(df_merge_groups.shape[1])]
df_merge_groups.columns = columns

for col in [col for col in df_merge_groups.columns if 'definition' in col]:
    df_merge_groups[f'variable_{col.split("_")[-1]}'] = df_merge_groups[col].map(flat_dict_def)


# sort based on the number of columns that are not nan 
df_merge_groups = df_merge_groups.reindex(df_merge_groups.count(axis=1).sort_values(ascending=False).index)

In [134]:
df_merge_groups.head()

,definition_1,definition_2,variable_1,variable_2
4,Both professional and non-professional individ...,informal (family/friends/mentors) and formal i...,supportive people,healthy support system
18,The extent to which alcohol misuse is accepted...,The rate of alcohol misuse within the community,community acceptance of alcohol misuse,community alcohol misuse rate
2,Adverse childhood experiences - can include ch...,None,adverse childhood experiences,NaN
0,"""Increases"" in mental health indicate a declin...",None,mental health,NaN
3,Being held responsible for one's actions by ot...,None,accountability,NaN

In [135]:
# save groups to excel sheet
file_path = str(parent_dir / 'results/SYNCH/JSON_file/RC/results sheets/data_dictionary/grouping/SYNCH_grouping_by_definition.xlsx')
# df_merge_groups.to_excel(file_path, sheet_name='threshold_0.65', index=False)

In [136]:
if not os.path.exists(file_path):   
    with pd.ExcelWriter(file_path, mode='w', engine='openpyxl') as writer:
        df_merge_groups.to_excel(writer, index=False, sheet_name='threshold_0.75')
else:   
    with pd.ExcelWriter(file_path, mode='a', engine='openpyxl', if_sheet_exists= "replace") as writer:
        df_merge_groups.to_excel(writer, index=False, sheet_name='threshold_0.75')

In [116]:
df_merge_groups.head()

,0,1
0,"""Increases"" in mental health indicate a declin...",None
1,A lack of social interaction/social support fr...,None
2,Adverse childhood experiences - can include ch...,None
3,Being held responsible for one's actions by ot...,None
4,Both professional and non-professional individ...,informal (family/friends/mentors) and formal i...

In [77]:
# df_merge_groups.iloc[1, 1]

'perpetration/victimization of violence by a or to a romantic partner through physical, sexual, mental/psychological, financial, social means'

In [89]:

# Print grouped variable names

for i, group in enumerate(groups):
    if len(group) > 1:
        print(f"Group {i + 1}: {group}")

len(groups)

Group 1: mental health
Group 2: isolation
Group 3: adverse childhood experiences
Group 4: accountability
Group 5: supportive people
Group 6: partner power and control over person
Group 7: child being abused in home
Group 8: couple's therapy
Group 9: resources that provide structure and support
Group 10: child welfare system intervention
Group 11: court order
Group 12: dire situations
Group 13: family functioning
Group 14: approval of therapy
Group 15: belief in a higher power
Group 16: negative treatment by child welfare case workers
Group 17: harmful romantic partners
Group 18: coping skills
Group 19: community acceptance of alcohol misuse
Group 20: community acceptance of intimate partner violence
Group 21: family emotional health
Group 22: community alcohol misuse rate
Group 23: community intimate partner violence rate
Group 24: re-entry facility
Group 25: incarceration
Group 26: stressful events
Group 27: children witness intimate partner violence
Group 28: death
Group 29: family and friend permissive intimate partner violence norms
Group 30: knowledge about healthy relationships
Group 31: healthy support system
Group 32: victimization stigma
Group 33: legal troubles
Group 34: leaving violent partner
Group 35: children removed from house
Group 36: desire to stop family cycle of violence and alcohol misuse
Group 37: intimate partner violence
Group 38: mental health resources
Group 39: being self sufficient
Group 40: sober environments
Group 41: partner willingness to change
Group 42: healthy relationship functioning
Group 43: alcohol misuse
Group 44: drug misuse
Group 45: wanting the violence by a partner or in a family to stop
Group 46: personal strength

46

In [51]:
# create a dictionary to swap the words that are bundled in the group. 
swap_dict = {}

for group in groups:
    if len(group) > 1:
        longest_name = max(group, key=len)
        swap_dict[longest_name] = group
swap_dict

swap_dict_reversed = {v: k for k, vv in swap_dict.items() for v in vv}
swap_dict_reversed

{'A lack of social interaction/social support from others - typically in reference to losing friends or family as a consequence of being with a violent partner (who "cuts off" a victim from others)': 'A lack of social interaction/social support from others - typically in reference to losing friends or family as a consequence of being with a violent partner (who "cuts off" a victim from others)',
 'perpetration/victimization of violence by a or to a romantic partner through physical, sexual, mental/psychological, financial, social means': 'A lack of social interaction/social support from others - typically in reference to losing friends or family as a consequence of being with a violent partner (who "cuts off" a victim from others)',
 "Adverse childhood experiences - can include child abuse or neglect, but more broadly also includes general lack of stability, safety, and healthy upbriniging in one's home, as well as exposures to chronic stressors and overall family maladjustment ": "Adverse childhood experiences - can include child abuse or neglect, but more broadly also includes general lack of stability, safety, and healthy upbriniging in one's home, as well as exposures to chronic stressors and overall family maladjustment ",
 'any experience (typically related to environments one is in/ traumatic experiences) that triggers stress ': "Adverse childhood experiences - can include child abuse or neglect, but more broadly also includes general lack of stability, safety, and healthy upbriniging in one's home, as well as exposures to chronic stressors and overall family maladjustment ",
 'Both professional and non-professional individuals (but in this case mostly professional or within a professional/setting) who provide you with emotional and possibly practical support': 'Both professional and non-professional individuals (but in this case mostly professional or within a professional/setting) who provide you with emotional and possibly practical support',
 'informal (family/friends/mentors) and formal individuals who offer emotional or practical support - as well as those who can advocate and stand up for individuals when victimized': 'Both professional and non-professional individuals (but in this case mostly professional or within a professional/setting) who provide you with emotional and possibly practical support',
 "From the perspective of the parent - observing one's child abused by others (typically by a partner) or abusing a child oneself": 'family members or friends who enable an abusive partner (either delliberate, such as retaliating against victims who call the police, or complicitly, through staying silient and giving covert approval)',
 "children witnessing violence between one's parent(s) ": 'family members or friends who enable an abusive partner (either delliberate, such as retaliating against victims who call the police, or complicitly, through staying silient and giving covert approval)',
 'family members or friends who enable an abusive partner (either delliberate, such as retaliating against victims who call the police, or complicitly, through staying silient and giving covert approval)': 'family members or friends who enable an abusive partner (either delliberate, such as retaliating against victims who call the police, or complicitly, through staying silient and giving covert approval)',
 'Intervention by child welfare/child protective services due to endangement of a child': 'Intervention by child welfare/child protective services due to endangement of a child',
 'Quality of the way that individuals are treated by child welfare caseworkers': 'Intervention by child welfare/child protective services due to endangement of a child',
 'Overall familial health through healthy interpersonal interaction, family stability, safety, and cohesiveness - taken from the perspective of an adult family member': 'Overall familial health through healthy interpersonal interaction, family stability, safety, and cohesiveness - taken from the perspective of an adult family member',
 'The mental/emotional health  of the family. Could refer to family raised in (as child) or family as an adult (e.g., with spouse and child). ': 'Overall familial health through healthy interpersonal interaction, family stability, safety, and cohesiveness - taken from the perspective of an adult family member',
 'Strategies and ability to carry out strategies related to dealling with internal and external negative experiences, broadly related to behavioral and emotional/mental regulation and resiliency': 'Strategies and ability to carry out strategies related to dealling with internal and external negative experiences, broadly related to behavioral and emotional/mental regulation and resiliency',
 "willpower, perseverence, related to the ability to change ones' behavior or situations, or to endure stress": 'Strategies and ability to carry out strategies related to dealling with internal and external negative experiences, broadly related to behavioral and emotional/mental regulation and resiliency',
 'The extent to which alcohol misuse is accepted in the community - alcohol misuse norms (permissive/positive)': 'The extent to which alcohol misuse is accepted in the community - alcohol misuse norms (permissive/positive)',
 'The rate of alcohol misuse within the community': 'The extent to which alcohol misuse is accepted in the community - alcohol misuse norms (permissive/positive)',
 'The extent to which intimate partner violence is accepted in the community - intimate partner violence norms (positive/permissive) - can also be considered the extent to which intimate partner violence is seen as an acceptable solution to conflict resolution': 'The extent to which intimate partner violence is accepted in the community - intimate partner violence norms (positive/permissive) - can also be considered the extent to which intimate partner violence is seen as an acceptable solution to conflict resolution',
 'The rate of intimate partner violence within the community': 'The extent to which intimate partner violence is accepted in the community - intimate partner violence norms (positive/permissive) - can also be considered the extent to which intimate partner violence is seen as an acceptable solution to conflict resolution',
 'the extent to which a partner is ammenable to, or actively desires to, change their behaviors / the way they interact with their partner/ to improve the relationship and reduce intimate partner violence within the relationship': 'The extent to which intimate partner violence is accepted in the community - intimate partner violence norms (positive/permissive) - can also be considered the extent to which intimate partner violence is seen as an acceptable solution to conflict resolution',
 'having a healthy internal working model - e.g., what a healthy partner "looks like", how one should be treated by their partner and how they should treat their partner in a healthy, nonviolent, and loving way': 'having a healthy internal working model - e.g., what a healthy partner "looks like", how one should be treated by their partner and how they should treat their partner in a healthy, nonviolent, and loving way',
 'the interpersonal health of a romantic relationship - e.g., communication, boundaries, cooperation, support, conflict resolution': 'having a healthy internal working model - e.g., what a healthy partner "looks like", how one should be treated by their partner and how they should treat their partner in a healthy, nonviolent, and loving way',
 'using alcohol - in reference to misuse': 'using alcohol - in reference to misuse',
 'using drugs -in reference to misuse': 'using alcohol - in reference to misuse'}

In [39]:
len(swap_dict_reversed)

4

In [40]:
# Swap the variable names in the data

cld_data_new = cld_data.copy()

for k, v in cld_data_new.items():
    for key, value in v[0].items():
        if value in swap_dict_reversed:
            v[0][key] = swap_dict_reversed[value]

In [41]:
variable_names = [list(v[0].values()) for k, v in cld_data_new.items()]

variable_names = sum(variable_names, [])

variable_names = np.sort(list(set(variable_names)))


print("number of originial unique nodes after cleaning the data: ", len(variable_names))

number of originial unique nodes after cleaning the data:  49

# write out the cleaned data to pickle

In [ ]:
# # Specify the file path where you want to save the pickled data
file_path = "results/SYNCH/JSON_file/RC_cld_data_cleaned_and_merged.json"

merged_file_path = str(parent_dir / file_path)

# Pickle dump the cld_data_new dictionary
with open(merged_file_path, "wb") as file:
    pickle.dump(cld_data_new, file)

c:\Users\GL665\Documents\Phrame-MentalMaps\results\SYNCH\JSON_file\RC_cld_data_cleaned_and_merged.json